#!/bin/bash

ATTEMPTS=${ATTEMPTS:-4}
N=1
while [[ $N -le $ATTEMPTS ]]; do
  N=$(( N + 1 ))
  ./tests && exit 0
  if [[ $? -ne 77 ]]; then
    exit $?
  fi

  (echo ; echo ;
   echo "  ***  TESTS FAILED ($N/$ATTEMPTS)"
   echo "  ***  DETECTED GO PANIC.  TRYING AGAIN..."
   echo ; echo) >&2
done

# vim:ft=bash
