#!/bin/bash

set -e

export GOPATH=${PWD}/gopath
export PATH=${PATH}:${GOPATH}/bin
cd ${GOPATH}/src/${MODULE}

# safe uses the Makefile, and doesn't run
# any `go test` / `go vet` stuff...

go version; echo; echo
make test
